### ISSUE TITLE
Is gh-pages broken?

### ISSUE THREAD

**Issue by yas375** [Lascorbe/CocoaConferences#88]
![2016-12-29_0909](https://cloud.githubusercontent.com/assets/217368/21549387/c497ec0a-cda6-11e6-8987-17574126a4dd.png)

**Comment by Lascorbe** [comment]
Damn, yes, looks like I broke it. Thanks for reporting!

**Comment by mariusc** [comment]
Fixed in 730c009f36d9aede8da6fb660d805b5d1ff240b5. 
I suspect it's a difference between the markdown flavours used by GitHub in their .md rendering on github.com and the flavour used by GitHub Pages.
More hands-on, to fix it I had to enter a newline between the table's title (the one starting with `###`) and the table
